DATASETS:
  DATA_FOLDER: /datasets/voc_coco/images/
  IMG_FORMAT: BGR
  NUM_WORKERS: 32
  SUPPORT_AVERAGE_TEST: true
  SUPPORT_JSON: /datasets/voc_coco/voc_2007_2012_trainval_base1.json
  SUPPORT_SIZE: 10
  SUPPORT_TEST_JSON: /datasets/voc_coco/voc_2007_test_base1.json
  TEST_JSON: /datasets/voc_coco/voc_2007_test_base1.json
  TRAIN_JSON: /datasets/voc_coco/voc_2007_2012_trainval_base1.json
MODEL:
  FINAL_TOKENS_AVERAGE_POOLING: false
  FINAL_TOKENS_NUMBER: 384
  FREEZE_BACKBONE: true
  META_ARCHITECTURE: facebook/dino-vits8
  MODEL_CLASS: models.LabelConfirmation3
  MODEL_FAMILY: DINO
MODEL_WEIGHTS: None
OUTPUT_DIR: /models/LC_VOC/base1/
SOLVER:
  BASE_LR: 0.0001
  BATCH_SIZE: 24
  EPOCH: 10
  ITER_HISTORY_PERIOD: 20
  LOSS1:
    ACTIVE: true
    MARGIN: 1
    REDUCTION: mean
    TYPE: torch.nn.TripletMarginLoss
    WEIGHT: 1
  LOSS2:
    REDUCTION: mean
    TYPE: torch.nn.CrossEntropyLoss
    WEIGHT: 1
  OPTIMIZER:
    TYPE: torch.optim.Adam
    WEIGHT_DECAY: 0
  SCHEDULER:
    GAMMA: 0.1
    STEP_SIZE: 5
    TYPE: torch.optim.lr_scheduler.StepLR
TEST_BATCH_SIZE: 32
TYPE: train
