DATASETS:
  DATA_FOLDER: /datasets/voc_coco/images
  DATA_FOLDER_PSEUDOS: /datasets/voc_coco/images
  DATA_FOLDER_SUPPORT: /datasets/voc_coco/images
  IMG_FORMAT: BGR
  NUM_WORKERS: 32
  PSEUDOS_JSON: /models/TFA/voc/faster_rcnn/mining/split_2/10shot_seed4/inference/coco_instances_results_filtrado_base2_nms_filt_score0.2.json
  SUPPORT_AVERAGE_TEST: true
  SUPPORT_JSON: /datasets/voc_coco/voc_2007_trainval_novel2_10shot_seed4.json
MODEL:
  FINAL_TOKENS_AVERAGE_POOLING: false
  FINAL_TOKENS_NUMBER: 384
  FREEZE_BACKBONE: true
  META_ARCHITECTURE: facebook/dino-vits8
  MODEL_CLASS: models.LabelConfirmation3
  MODEL_FAMILY: DINO
MODEL_WEIGHTS: /models/LC_VOC/2split_10shot_4seed/final_model_epoch_9.pth
OUTPUT_DIR: /models/TFA/voc/faster_rcnn/mining/split_2/10shot_seed4/inference/LC_output
SAVE_NAME: coco_instances_results_filtrado_base2_nms_filt_score0.2.json_LC_OUTPUT.json
TEST_BATCH_SIZE: 32
